// Generated with Shader Minifier 1.4.0 (https://github.com/laurentlb/Shader_Minifier/)
#ifndef SHADER_INCLUDES_H_
# define SHADER_INCLUDES_H_

static const char* post_frag =
 "#version 460\n"
 "out vec4 C;"
 "layout(binding=5) uniform sampler2D tex_render;"
 "layout(binding=0,r32ui) uniform coherent uimage2D tex_r;"
 "layout(binding=1,r32ui) uniform coherent uimage2D tex_g;"
 "layout(binding=2,r32ui) uniform coherent uimage2D tex_b;"
 "float t(vec3 v)"
 "{"
   "return dot(v,vec3(.2126729,.7151522,.072175));"
 "}\n"
 "#define SPAN_MAX (8.0)\n"
 "#define REDUCE_MIN (1.0/128.0)\n"
 "#define REDUCE_MUL (1.0/32.0)\n"
 "vec4 t(sampler2D v,vec2 x)"
 "{"
   "vec2 f=vec2(textureSize(v,0));"
   "f=1./f;"
   "float u=t(texture(v,x).xyz),i=t(texture(v,x+vec2(-.5)*f).xyz),y=t(texture(v,x+vec2(.5)*f).xyz),s=t(texture(v,x+vec2(.5,-.5)*f).xyz),m=t(texture(v,x+vec2(-.5,.5)*f).xyz);"
   "vec2 c=vec2(m+y-i-s,i+m-s-y);"
   "float r=1./(min(abs(c.x),abs(c.y))+max((i+s+m+y)*REDUCE_MUL,REDUCE_MIN));"
   "c=clamp(c*r,-SPAN_MAX,SPAN_MAX)*f;"
   "vec4 a=.5*(texture(v,x-c*(1./6.))+texture(v,x+c*(1./6.))),l=a*.5+.25*(texture(v,x-c*.5)+texture(v,x+c*.5));"
   "r=t(l.xyz);"
   "return r<min(u,min(min(i,s),min(m,y)))||r>max(u,max(max(i,s),max(m,y)))?"
     "a:"
     "l;"
 "}"
 "void main()"
 "{"
   "vec2 x=gl_FragCoord.xy/vec2(textureSize(tex_render,0));"
   "C=pow(max(t(tex_render,x),0.),vec4(.4545));"
   "imageStore(tex_r,ivec2(gl_FragCoord.xy),ivec4(0));"
   "imageStore(tex_g,ivec2(gl_FragCoord.xy),ivec4(1));"
   "imageStore(tex_b,ivec2(gl_FragCoord.xy),ivec4(2));"
   "C.w=1.;"
 "}";

static const char* scene_i2f_frag =
 "#version 460\n"
 "out vec4 C;"
 "layout(binding=0,r32ui) uniform coherent uimage2D tex_r;"
 "layout(binding=1,r32ui) uniform coherent uimage2D tex_g;"
 "layout(binding=2,r32ui) uniform coherent uimage2D tex_b;"
 "void main()"
 "{"
   "ivec2 x=ivec2(gl_FragCoord);"
   "C=vec4(vec3(imageLoad(tex_b,x).x)/2048.,1);"
 "}";

static const char* scene_jizz_comp =
 "#version 460\n"
 "layout(local_size_x=256,local_size_y=1,local_size_z=1)in;"
 "uniform float u_t;"
 "uniform int F;"
 "layout(binding=0,r32ui) uniform coherent uimage2D tex_r;"
 "layout(binding=1,r32ui) uniform coherent uimage2D tex_g;"
 "layout(binding=2,r32ui) uniform coherent uimage2D tex_b;"
 "const float x=60./90.,v=acos(-1.),s=v*2.,f=acos(-1.),u=f*2.;"
 "mat3 p(float v,float x)"
 "{"
   "return mat3(1,0,0,0,1,0,v,x,1);"
 "}"
 "mat3 p(float v)"
 "{"
   "return mat3(v,0,0,0,v,0,0,0,1);"
 "}"
 "mat2 n(float v)"
 "{"
   "return mat2(cos(v),-sin(v),sin(v),cos(v));"
 "}"
 "uint i;"
 "uint r(uint v)"
 "{"
   "v=(v^v>>16)*2146121005U;"
   "v=(v^v>>15)*2221713035U;"
   "return v^v>>16;"
 "}"
 "float m(uint v)"
 "{"
   "return float(r(uint(v)))/float(4294967295U);"
 "}"
 "float m()"
 "{"
   "i=r(i);"
   "return float(i)/float(4294967295U);"
 "}"
 "vec2 n()"
 "{"
   "return vec2(m(),m());"
 "}"
 "vec3 p()"
 "{"
   "return vec3(m(),m(),m());"
 "}"
 "vec2 r()"
 "{"
   "vec2 v=n();"
   "return vec2(sin(v.x*s),cos(v.x*s))*sqrt(v.y);"
 "}"
 "vec2 y;"
 "ivec2 e(vec3 v)"
 "{"
   "v.xy+=r()*abs(v.z)*.02;"
   "return ivec2((v.xy+vec2(y.x/y.y,1)*.5)*vec2(y.y/y.x,1)*y);"
 "}"
 "float a[20]={1.,0.,0.,0.,1.,1.,0.,1.,0.,0.,0.,0.,0.,0.,1.,1.,0.,1.,0.,0.};"
 "float h(float y)"
 "{"
   "return sin(-y*v-v/2.)*.5+.5;"
 "}"
 "float e(float x,float y)"
 "{"
   "return x>0.?"
     "1.-exp(-x*y):"
     "0.;"
 "}"
 "vec3 e(vec3 v,float x,float y)"
 "{"
   "vec4 i=vec4(0);"
   "for(int f=0;f++<5;)"
     "v.yz*=n(4.5),v.xy*=n(1.5),v+=sin(v.zxy),i=(i+vec4(cross(cos(v),sin(v.yzx)),1))/x,v*=y;"
   "return i.xyz/i.w;"
 "}"
 "void h(ivec2 v,vec3 i)"
 "{"
   "ivec3 u=ivec3(i*2048);"
   "imageStore(tex_r,v,ivec4(u.x));"
   "imageStore(tex_g,v,ivec4(u.y));"
   "imageStore(tex_b,v,ivec4(u.z));"
 "}"
 "void m(ivec2 v,vec3 i)"
 "{"
   "ivec3 u=ivec3(i*2048);"
   "imageAtomicAdd(tex_r,v,u.x);"
   "imageAtomicAdd(tex_g,v,u.y);"
   "imageAtomicAdd(tex_b,v,u.z);"
 "}"
 "void n(ivec2 u,int f)"
 "{"
   "i=uint(f)+125125u+uint(F);"
   "float t=max(0.,u_t/x-20.),r=0.;"
   "for(int i=0;i<20;i++)"
     "r+=a[i];"
   "r*=floor(t/5.);"
   "for(int v=0;v<20;v++)"
     "{"
       "int i=int(mod(floor(t*4.),20.));"
       "if(v>i)"
         "break;"
       "r+=a[v]*e(float(i-v)+fract(t*4.),3.);"
     "}"
   "r=r*.25+u_t*.4*step(1.,u_t/x/20.);"
   "vec2 c=vec2(1,0);"
   "for(int i=0;i<u.x/16;i++)"
     "{"
       "c.x-=16.*(2.+m()*.1)/float(u.x);"
       "float t=m(f%7),y=t+r,s=0.;"
       "for(int v=0;v<4;v++)"
         "{"
           "float i=mix(m(f%7+v*4+1+int(y)),m(f%7+v*4+2+int(y)),h(fract(y)))-float(v)*.4-t*.8+.3,u=(mix(m(f%7+v*4+3+int(y)),m(f%7+v*4+4+int(y)),h(fract(y)))*2.-1.)*smoothstep(0.,1.,u_t/x/20.);"
           "s+=smoothstep(0.,1.,(i-c.x)*4.)*u*.2;"
         "}"
       "vec3 l=vec3(vec2(c.x,s),pow(sin(c.x*1.8-t*18.-u_t*.9)*.5+.5,1999.));"
       "if(m()<smoothstep(.1,0.,u_t/x/20.))"
         "return;"
       "if(m()>smoothstep(3.90625,3.75,u_t/x/20.))"
         "return;"
       "m(e(vec3(l.xy*n(smoothstep(4.,2.,u_t/x/20.)*v/2.),l.z)),vec3(1));"
     "}"
 "}"
 "void r(ivec2 u,int y)"
 "{"
   "i=uint(y)+125125u+uint(F);"
   "vec3 t=vec3(1)*u_t*.3,r=p()*2.-1.,s=floor(r*8.+t),c=fract(r*8.+t),z=e(s*9.+u_t*.1,1.,1.)*.5;"
   "c=(c*2.-1.)*2.;"
   "for(float v=-1.;v<1.5;v+=1.)"
     "for(float i=-1.;i<1.5;i+=1.)"
       "for(float u=-1.;u<1.5;u+=1.)"
         "{"
           "if(abs(v)+abs(i)+abs(u)<.0015)"
             "continue;"
           "vec3 x=vec3(v,i,u);"
           "x=(x+e((s+x)*9.+u_t*.1,1.,1.)*.5-z)/2.;"
           "float y=acos(dot(c,x)/(length(c)*length(x)));"
           "if(abs(y)>f/2.)"
             "continue;"
           "c=normalize(c)*min(length(c),length(x)/cos(y));"
         "}"
   "r=(s+.5+z+c-t)/8.;"
   "r.xy*=vec2(3,4)*.5;"
   "r.zx*=n(.3);"
   "r.yz*=n(.7);"
   "m(e(vec3(r.xy*n(smoothstep(4.,2.,u_t/x/20.)*v/2.),r.z)),vec3(exp(-abs(r.z)*110.-7.*smoothstep(4.,1.,u_t/x/20.))));"
 "}"
 "void h(uint v,uint x,mat3 y)"
 "{"
   "vec2[5] s={vec2(1,-1),vec2(1,0),vec2(1),vec2(0,1),vec2(-1,1)};"
   "i=x;"
   "mat2 t=mat2(sign(m()-.5),0,0,sign(m()-.5));"
   "uint[3] c={r(x)%6,r(x+1)%6,r(x+2)%6};"
   "int[3] a={int(r(x+6)%3)-1,int(r(x+7)%3)-1,int(r(x+8)%3)-1};"
   "int b=3;"
   "float z=.2;"
   "for(int i=0;i<3;i++)"
     "if(c[i]>=5)"
       "b--;"
   "if(b<=0)"
     "c[0]=r(x+3)%6,c[1]=r(x+4)%6,c[2]=r(x+5)%5,z+=.7;"
   "bool g=m()<z;"
   "i=v;"
   "z=m();"
   "v=r(i+1)%(g?"
     "4:"
     "3);"
   "vec2 l=vec2(0);"
   "if(v>=3)"
     "l=vec2(cos(z*u),sin(z*u));"
   "else"
     "{"
       "uint i=c[v];"
       "if(i>=5)"
         "return;"
       "vec2 u=t*vec2(-1),x=t*s[i];"
       "l=mix(u,x,z)+mat2(0,-1,1,0)*normalize(x-u)*float(a[v])*cos(z*f-f/2.)*.3;"
     "}"
   "m(e(vec3((y*vec3(l,1)).xy,0)),vec3(1));"
 "}"
 "void w(ivec2 v,int u)"
 "{"
   "i=uint(u)+125125u+uint(F);"
   "h(uint(u),10,p(.1)*p(-4.5,0.));"
   "h(uint(u),3,p(.1)*p(-1.5,0.));"
   "h(uint(u),17,p(.1)*p(1.5,0.));"
   "h(uint(u),12,p(.1)*p(4.5,0.));"
 "}"
 "void d(ivec2 v,int u)"
 "{"
   "i=uint(u)+125125u+uint(F);"
   "float y=smoothstep(5.5,5.75,u_t/x/20.),s=mix(10.,1.,y),f=mix(3.,1.2,y);"
   "int t=int(mix(1.,6.,max(0.,y-m()*.1*(1.-y))));"
   "vec4 c[8];"
   "for(int v=0;v<8;v++)"
     "{"
       "if(v>=t)"
         "break;"
       "i=23924u+uint(v);"
       "float u=float(v)+u_t*.1;"
       "c[v].xyz=e(vec3(u),1.,1.)*float(t)*.08;"
       "c[v].w=mix(.1,.13,m());"
     "}"
   "for(int i=0;i<6;i++)"
     "for(int v=0;v<64;v++)"
       "{"
         "if(v/8>=t||v%8>=t)"
           "continue;"
         "if(v/8==v%8)"
           "continue;"
         "vec4 i=c[v/8],u=c[v%8];"
         "vec3 y=i.xyz-u.xyz;"
         "float f=i.w+u.w+.15-length(y);"
         "f*=exp(abs(f)*1.2)-1.;"
         "c[v/8].xyz+=normalize(y)*f;"
         "c[v/8].xyz-=normalize(c[v/8].xyz)*pow(length(c[v/8].xyz),3.)*s;"
       "}"
   "for(int v=0;v<8;v++)"
     "{"
       "if(v>=t)"
         "break;"
       "i=uint(u)+125325u+uint(F);"
       "vec3 x=c[v].xyz;"
       "float s=c[v].w;"
       "vec3 y=normalize(p()*2.-1.);"
       "y=x+y*(1.+e(y+x*8.+u_t*.6,1.,8.)*.15)*s;"
       "y.xz*=n(u_t);"
       "y.zy*=n(u_t*.7);"
       "m(e(y*f),vec3(.02));"
     "}"
 "}"
 "void c(ivec2 v,int u)"
 "{"
   "i=uint(u)+125125u+uint(F);"
   "float x=m()*2.-1.;"
   "x*=4.;"
   "float y=step(.5,m())*f,s=m()*.3;"
   "vec3 t=vec3(cos(x*3.+y-u_t),x+s,sin(x*3.+y-u_t));"
   "m(e(t*.15-vec3(.65,0,0)),vec3(.1));"
 "}"
 "void l(ivec2 v,int u)"
 "{"
   "i=uint(u)+125125u+uint(F);"
   "vec2 f=vec2(.4,.3),s=vec2(.55,-.3);"
   "float y=step(f.x/(f.x+f.y),m()),c=sign(m()-.5);"
   "vec2 t=mix(vec2(f.x*(m()-.5),c*f.y/2.),vec2(c*f.x/2.,f.y*(m()-.5)),y);"
   "c=t.x+t.y*.2-u_t*22.;"
   "t+=.1*vec2(.4,.8)*e(vec3(floor(c*4.)+tanh((fract(c*4.)*2.-1.)*8.)*.5+.5),1.,2.).x*step(5.5,u_t/x/20.);"
   "m(e(vec3(t+s,0)),vec3(1));"
   "m(e(vec3((s-vec2(f.x/2.,-f.y/2.))*m(),0)),vec3(1));"
   "t=n()*f*8.;"
   "t=floor(t);"
   "y=t.x+t.y*.2-u_t*22.;"
   "f=vec2(.4,.8)*e(vec3(floor(y*4.)+tanh((fract(y*4.)*2.-1.)*8.)*.5+.5),1.,2.).x*step(5.5,u_t/x/20.);"
   "h(u,uint(min(t.y*4.+t.x,(u_t/x-90.)*2.)),p(s.x+(t.x/4.-.375)*.3+f.x*.03,s.y+(t.y/4.-.275)*.3+f.y*.03)*p(.02));"
 "}"
 "void b(ivec2 v,int u)"
 "{"
   "i=uint(u)+125125u+uint(F);"
   "vec2 f=vec2(.1,.05),t=floor(n()*vec2(16,8)),s=t;"
   "t=t/vec2(4,8)-vec2(1,.425);"
   "vec2 c=vec2(0);"
   "if(e(vec3(s,u_t-pow(m(),55.)*.2),1.,1.).x>0.)"
     "{"
       "float v=step(f.x/(f.x+f.y),m()),u=sign(m()-.5);"
       "c=mix(vec2(f.x*(m()-.5),u*f.y/2.),vec2(u*f.x/2.,f.y*(m()-.5)),v);"
     "}"
   "else"
     " c=(n()*2.-1.)*vec2(f)/2.;"
   "c.x+=c.y*.2;"
   "m(e(vec3(c+t,0)),vec3(.1));"
   "float y=step(.5,m()),r=pow(1.-clamp((u_t/x/20.-5.)*2.,0.,1.),.6);"
   "for(int v=7;v>=0;v--)"
     "{"
       "if(v<int(s.y))"
         "break;"
       "for(int i=0;i<16;i++)"
         "{"
           "if(int(s.y)-v<i-int(s.x))"
             "break;"
           "if(r*2.-1.<e(vec3(float(i),float(v),y)+u_t-pow(m(),15.)*.05,1.,1.).x)"
             "return;"
         "}"
     "}"
   "m(e(vec3(t+vec2(1,-y)/vec2(8)*m()+vec2(.5,0)/vec2(8),0)),vec3(1));"
 "}"
 "float b(vec2 v)"
 "{"
   "v=abs(v);"
   "return max(v.x,v.y);"
 "}"
 "float c(vec2 v)"
 "{"
   "vec2 u=abs(v);"
   "return mix(b(vec2(v.x-v.y,v.x+v.y))/sqrt(2.),length(u-(u.x*u.x+u.y*u.y)/(2.*(u.x+u.y))),step(0.,v.y))-.5;"
 "}"
 "void R(ivec2 v,int u)"
 "{"
   "i=uint(u)+125125u+uint(u_t);"
   "vec3 f=vec3(0),c=e(vec3(r(i)),1.,1.);"
   "for(int v=0;v<24;v++)"
     "{"
       "if(float(v-12)/12.>c.x)"
         "break;"
       "float y=m(v+i*24);"
       "c.yz=e(c,1.,2.).xy;"
       "vec2 u=normalize(floor((c.yz+1.)*1.5)-1.);"
       "float t=1.-h(clamp(u_t/x/20.-6.,0.,1.));"
       "vec3 r=mix(f,f+vec3(u,0),y);"
       "r.x+=t*4.;"
       "r.yz*=n(.6+t);"
       "r.xy*=n(.2+t);"
       "h(e(r*(1.-t)),vec3(.5+float(v)/24.));"
       "f.xy+=u;"
     "}"
 "}"
 "float g(vec2 v,float t)"
 "{"
   "v.x=abs(v.x);"
   "v.x-=t/2.;"
   "return v.x>0.?"
     "max(abs(v.x),abs(v.y)):"
     "abs(v.y);"
 "}"
 "float R(vec2 v)"
 "{"
   "return min(g(v-vec2(.95,0),1.5),min(g(v*n(u/8.)-vec2(.5,0),1.),g(v*n(-u/8.)-vec2(.5,0),1.)));"
 "}"
 "float d(vec2 v)"
 "{"
   "return min(R(vec2(-v.x+1.5,v.y)*1.25)-.3,c(v+vec2(1,0)));"
 "}"
 "void A(ivec2 v,int u)"
 "{"
   "i=uint(u)+125125u;"
   "float y=m();"
   "vec2 f=e(vec3(float(i%4096),u_t*.2,0),3.,1.1).xy,s=f+e(vec3(float(i%4096),u_t*.2,1),1.,1.1).xy*.3,t=normalize(s-f);"
   "float c=0.,r=0.,z=0.,l=1.;"
   "for(int i=0;i<128;i++)"
     "{"
       "vec2 v=f+t*r;"
       "c=min(d(v*2.+vec2(3.-(u_t/x/20.-10.)*2.,0))*l,length(v-s));"
       "if(dot(v-f,t)>0.&&abs(length(v-s))<.0015)"
         "break;"
       "if(c<.0015)"
         "{"
           "l=-l;"
           "r+=3*.0015;"
           "continue;"
         "}"
       "if(l<0.)"
         "z+=c;"
       "r+=c;"
     "}"
   "m(e(vec3(mix(f,s,y),y)),vec3(pow(1.-z/length(f-s),12.))*.02);"
 "}"
 "void S(ivec2 v,int y)"
 "{"
   "float t=smoothstep(10.5,11.5,u_t/x/20.);"
   "i=uint(y)+1259u;"
   "int c=2+int(smoothstep(10.,10.5,u_t/x/20.)*14.);"
   "float s=floor(u_t/x)+e(fract(u_t/x),2.5);"
   "vec3 r=normalize(e(vec3(float(i%c)*.25,s*.2+4.,0),1.,1.))*.8;"
   "r.z+=2.;"
   "vec3 l=normalize(e(vec3(float((i+1)%c)*.25,s*.2+4.,0),1.,1.))*.8;"
   "l.z+=2.;"
   "uint g=i%c;"
   "vec2 a=r.xy/r.z;"
   "m(e(vec3(mix(vec2(0),a,m()),0)),vec3(.001));"
   "m(e(vec3(mix(l.xy/l.z,a,m()),0)),vec3(.001));"
   "l=normalize(p()-.5);"
   "l+=t*e(l,1.,1.2);"
   "l+=t*e(l,1.,1.2);"
   "l+=t*e(l,1.,1.2);"
   "l+=t*e(l,1.,1.2);"
   "l+=t*e(l,1.,1.2);"
   "vec2 b=vec2(atan(l.x,-l.z),atan(l.y,-l.z));"
   "b.x=fract(b.x/u-u_t*.2)*u;"
   "s=step(0.,d(b-vec2(f,0)));"
   "m(e(l*.4+vec3(0,0,2)),vec3(.011*s));"
   "h(y,g,p(a.x+(m()*2.-1.)*.002,a.y+(m()*2.-1.)*.002)*p(.04/r.z));"
 "}"
 "void o(ivec2 v,int u)"
 "{"
   "i=uint(u)+125125u;"
   "float y=m();"
   "vec2 f=e(vec3(float(i%4096),u_t*.2,0),3.,1.1).xy,s=f+e(vec3(float(i%4096),u_t*.2,1),1.,1.1).xy*.6;"
   "m(e(vec3(mix(f,s,y),y)),vec3(7e-4));"
 "}"
 "void B(ivec2 v,int u)"
 "{"
   "i=uint(u)+2225u;"
   "uint y=uint(5.*u_t/x),f=i%4+r(y);"
   "vec2 c=vec2(.7,.3),s=(n()*2.-1.)*.005,l=vec2(sign(m(f)-.5),sign(m(f+99)-.5));"
   "float t=m(f+y);"
   "if(m(i)>pow(2e4,t-1.))"
     "return;"
   "h(r(f)+u,f,p(c.x*l.x,c.y*l.y)*p(s.x,s.y)*p(.1));"
 "}"
 "void main()"
 "{"
   "y=vec2(imageSize(tex_g));"
   "ivec2 v=ivec2(imageSize(tex_b));"
   "int u=int(gl_GlobalInvocationID.x)+int(gl_GlobalInvocationID.y)*v.x;"
   "i=uint(u+1245124);"
   "if(u_t/x/20.<3.90625)"
     "o(v,u),n(v,u),r(v,u);"
   "else if(u_t/x/20.<4.)"
     "o(v,u),w(v,u),r(v,u);"
   "else if(u_t/x/20.<6.)"
     "{"
       "o(v,u);"
       "if(u_t/x/20.>5.&&u_t/x/20.<5.5)"
         "b(v,u);"
       "else"
         "{"
           "d(v,u);"
           "if(u_t/x/20.>4.5)"
             "c(v,u),l(v,u);"
         "}"
     "}"
   "else if(u_t/x/20.<7.)"
     "o(v,u),R(v,u),B(v,u);"
   "else if(u_t/x/20.<8.73)"
     "o(v,u),R(v,u);"
   "else"
     "{"
       "o(v,u);"
       "if(u_t/x/20.<11.)"
         "S(v,u),B(v,u);"
       "else if(u_t/x/20.<12.)"
         "A(v,u);"
     "}"
 "}";

static const char* scene_sandbox_frag =
 "#version 460\n"
 "vec2 z,U;"
 "out vec4 C;"
 "layout(binding=3) uniform sampler2D comp_tex;"
 "layout(binding=4) uniform sampler2D back_tex;"
 "uniform float u_t;"
 "uniform bool reaction_diffusion;"
 "const float N=60./90.,D=acos(-1.),E=D*2.;"
 "vec2 k;"
 "const float G=acos(-1.),X=G*2.;"
 "mat2 n(float v)"
 "{"
   "return mat2(cos(v),-sin(v),sin(v),cos(v));"
 "}"
 "vec3 A(uvec3 v)"
 "{"
   "v=(v>>8U^v.yzx)*1103773245U;"
   "v=(v>>8U^v.yzx)*1103773245U;"
   "v=(v>>8U^v.yzx)*1103773245U;"
   "return vec3(v)*(1./float(4294967295U));"
 "}"
 "vec3 B(vec3 v)"
 "{"
   "uvec3[8] f;"
   "f[0]=uvec3(round(abs(v)+vec3(-.5)));"
   "f[1]=uvec3(round(abs(v)+vec3(.5,-.5,-.5)));"
   "f[2]=uvec3(round(abs(v)+vec3(-.5,.5,-.5)));"
   "f[3]=uvec3(round(abs(v)+vec3(.5,.5,-.5)));"
   "f[4]=uvec3(round(abs(v)+vec3(-.5,-.5,.5)));"
   "f[5]=uvec3(round(abs(v)+vec3(.5,-.5,.5)));"
   "f[6]=uvec3(round(abs(v)+vec3(-.5,.5,.5)));"
   "f[7]=uvec3(round(abs(v)+vec3(.5)));"
   "v=smoothstep(0.,1.,fract(abs(v)));"
   "return mix(mix(mix(A(f[0]),A(f[1]),v.x),mix(A(f[2]),A(f[3]),v.x),v.y),mix(mix(A(f[4]),A(f[5]),v.x),mix(A(f[6]),A(f[7]),v.x),v.y),v.z)*2.-1.;"
 "}"
 "vec3 e(vec3 v,float x,float u)"
 "{"
   "vec4 f=vec4(0);"
   "for(int i=0;i++<5;)"
     "v.yz*=n(4.5),v.xy*=n(1.5),v+=sin(v.zxy),f=(f+vec4(cross(cos(v),sin(v.yzx)),1))/x,v*=u;"
   "return f.xyz/f.w;"
 "}"
 "float S(vec2 v)"
 "{"
   "float f=length(v);"
   "for(int i=0;i<5;i++)"
     "{"
       "float u=float[5](.6,.55,-1.,.65,0.)[i];"
       "vec2 s=sin((float(i)+vec2(0,1.5))*G/3.);"
       "f=min(f,length(clamp(dot(s,v),u,1.)*s-v)-.16);"
     "}"
   "return f;"
 "}"
 "float H[20]={1.,0.,0.,0.,0.,0.,0.,1.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.};"
 "float e(float v,float y)"
 "{"
   "return v>0.?"
     "1.-exp(-v*y):"
     "0.;"
 "}"
 "float g(vec3 v)"
 "{"
   "v.zx*=n(u_t*2.77);"
   "v.x=abs(v.x);"
   "v.zy*=n(u_t*.33);"
   "v.x=abs(v.x);"
   "v.yx*=n(u_t*.23);"
   "v.y=abs(v.y);"
   "v.zy*=n(u_t*.43);"
   "v.x=abs(v.x);"
   "v.zx*=n(u_t*.97);"
   "v.x=abs(v.x);"
   "v.yx*=n(u_t*.63);"
   "v.y=abs(v.y);"
   "v.zy*=n(u_t*.13);"
   "v.x=abs(v.x);"
   "v.zx*=n(u_t*.87);"
   "v.x=abs(v.x);"
   "v.yx*=n(u_t*.55);"
   "return max(abs(v.x),max(abs(v.y),abs(v.z)));"
 "}"
 "float b(vec2 v)"
 "{"
   "v=abs(v);"
   "return max(v.x,v.y);"
 "}"
 "float c(vec2 v)"
 "{"
   "vec2 u=abs(v);"
   "return mix(b(vec2(v.x-v.y,v.x+v.y))/sqrt(2.),length(u-(u.x*u.x+u.y*u.y)/(2.*(u.x+u.y))),step(0.,v.y))-.5;"
 "}"
 "float l(vec3 v)"
 "{"
   "v.z-=1.5;"
   "v.xz*=n(u_t);"
   "return g(v)-1.;"
 "}"
 "vec3 o(vec3 v)"
 "{"
   "return normalize(vec3(l(v+vec3(.0015,0,0))-l(v-vec3(.0015,0,0)),l(v+vec3(0,.0015,0))-l(v-vec3(0,.0015,0)),l(v+vec3(0,0,.0015))-l(v-vec3(0,0,.0015))));"
 "}"
 "vec3 w(vec2 v)"
 "{"
   "vec3 f=vec3(0,0,-1),u=normalize(vec3(-v,1)),i=f,t=vec3(.9),s=vec3(1),y=normalize(vec3(cos(u_t),0,sin(u_t)));"
   "int c=8;"
   "float x=1.,r,m;"
   "for(int v=0;v<256;v++)"
     "{"
       "i=f+u*r;"
       "m=l(i)*x;"
       "if(m<.0015)"
         "{"
           "vec3 v=refract(u,o(i)*x,x>0.?"
             "1.5:"
             "1./1.5),l=vec3(.5);"
           "if(x<0.)"
             "s*=exp(-.5*r)*l;"
           "s*=mix(vec3(1),l,.5);"
           "t=t+exp((dot(-o(i),y)*.5-.5)*32.)*vec3(1)*2.+exp((dot(-u,y)*.5-.5)*16.)*vec3(1)*.1;"
           "if(length(v)>.0015)"
             "u=v,x*=-1.;"
           "else"
             " u=reflect(u,o(i)*x);"
           "r=0.;"
           "f=i+u*.0015*3.;"
           "c--;"
           "if(c<=0)"
             "break;"
         "}"
       "else"
         " r+=m*.5;"
     "}"
   "return t*s;"
 "}"
 "vec3 I(vec2 v)"
 "{"
   "vec2 i=v,f=vec2(0);"
   "for(int u=0;u<99;u++)"
     "{"
       "float y=u_t*.3;"
       "vec3 c=e(vec3(y,0,0),.1,.1);"
       "f+=normalize(c.xy-v)*tanh(dot(vec2(cos(c.z*X),sin(c.z*X)),normalize(c.xy-v)))*9./length(c.xy-v);"
       "c=e(vec3(0,y,0),.1,.1);"
       "f+=normalize(c.xy-v)*tanh(dot(vec2(cos(c.z*X),sin(c.z*X)),normalize(c.xy-v)))*5./length(c.xy-v);"
       "c=e(vec3(0,0,y),.1,.1);"
       "f=(f+normalize(c.xy-v)*tanh(dot(vec2(cos(c.z*X),sin(c.z*X)),normalize(c.xy-v)))*4./length(c.xy-v))*.9;"
       "i+=f;"
     "}"
   "vec3 t=sin(vec3(0,1,2)+length(f)*.1)*.5+.5;"
   "float u=-S(v*1.4);"
   "u=u>0.?"
     "1.:"
     "exp(u*mix(1e2,8e2,e(vec3(z*3.,u_t),.1,9.).x*.5+.7)*pow(1.-clamp(u_t/N/20.-13.,0.,1.),2.));"
   "return t*u;"
 "}"
 "float J(vec2 v)"
 "{"
   "float f=99.;"
   "for(float i=0.;i<6.;i++)"
     "{"
       "vec2 u=v*n(X*i/(sin(u_t*.47)*1.5+4.5));"
       "f=min(f,u.x+sin(u.y)*(sin(u_t*.7)*.5+.5)+1.);"
     "}"
   "return abs(f-.5)-.05;"
 "}"
 "vec2 K(vec2 v)"
 "{"
   "return normalize(vec2(J(v+vec2(.0015,0))-J(v-vec2(.0015,0)),J(v+vec2(0,.0015))-J(v-vec2(0,.0015))));"
 "}"
 "float g(vec2 v,float t)"
 "{"
   "v.x=abs(v.x);"
   "v.x-=t/2.;"
   "return v.x>0.?"
     "max(abs(v.x),abs(v.y)):"
     "abs(v.y);"
 "}"
 "float R(vec2 v,float u)"
 "{"
   "return min(g(v-vec2(u/2.+.2,0),u),min(g(v*n(X/8.)-vec2(.5,0),1.),g(v*n(-X/8.)-vec2(.5,0),1.)));"
 "}"
 "float d(vec2 v)"
 "{"
   "return min(R(vec2(-v.x+1.5,v.y)*1.25,1.5)-.3,c(v+vec2(1,0)));"
 "}"
 "vec3 L(vec2 v)"
 "{"
   "vec3 f=vec3(0);"
   "float i=0.;"
   "for(int v=0;v<20;v++)"
     "i+=H[v];"
   "i*=floor(u_t/N/5.);"
   "for(int v=0;v<20;v++)"
     "{"
       "int u=int(mod(floor(u_t*4./N),20.));"
       "if(v>u)"
         "break;"
       "i+=H[v]*e(float(u-v)+fract(u_t*4./N),1.5);"
     "}"
   "vec2 u=vec2(-1,-.5);"
   "float y=e(u_t/N/5.-33.,3.)*9.25-8.25;"
   "vec2 x=u*max(0.,min(1.,y)),s=v*n(u_t*.1+i*.3),t=s,r=vec2(0);"
   "float c=0.;"
   "for(int u=0;u<32;u++)"
     "{"
       "vec2 y=t*2.*n(float(u)*.06-e(vec3(-i*.4+length(v-x)*1.7),5.,1.).x*.5);"
       "c=J(y);"
       "f+=vec3(length(t-s))*.1;"
       "r-=K(y)*c;"
       "t+=r;"
       "r*=.5;"
     "}"
   "return vec3(1)*pow(vec3(1.-exp(-mix(f,vec3(1),step(R((v-u*y)*2.*n(atan(u.y,-u.x)),6.),.2)).x*.5)),vec3(6));"
 "}"
 "float M(vec2 v)"
 "{"
   "return-d(v*.2+vec2(3.-(u_t/N/20.-10.)*2.,0));"
 "}"
 "vec3 O(vec2 v)"
 "{"
   "vec2 u=floor(v*4.),f=fract(v*4.);"
   "int i=3;"
   "float c=M(u+.5);"
   "if(c.x>0.)"
     "{"
       "i--;"
       "u+=floor(f*2.)/2.,f=fract(f*2.);"
       "c=M(u+.25);"
       "if(c.x>.1)"
         "{"
           "i--;"
           "u+=floor(f*2.)/4.,f=fract(f*2.);"
           "c=M(u+.125);"
           "if(c.x>.15)"
             "i--,u+=floor(f*2.)/8.,f=fract(f*2.),c=e(vec3(u,0),1.,5.).x;"
         "}"
     "}"
   "c=1.;"
   "f=mix(f,vec2(1.-f.x,f.y),mod(u.x*pow(2.,float(3-i))+u.y*pow(2.,float(3-i)),2.));"
   "{"
     "vec2 y=1.-f.x>f.y?"
       "f:"
       "vec2(1)-f;"
     "float x=step(length(y),.5)*(cos(length(y)*X*pow(2.,float(i)))*.5+.5);"
     "c=min(c,x);"
   "}"
   "{"
     "vec2 y=f.x>f.y?"
       "vec2(1.-f.x,f.y):"
       "vec2(f.x,1.-f.y);"
     "c=mix(c,cos(length(y)*X*pow(2.,float(i)))*.5+.5,step(length(y),.5));"
   "}"
   "return pow(vec3(sin(-c*3.)*.5+.5),vec3(1.+sin(length(v)*2.-2.*u_t/N)*.35));"
 "}"
 "float I(float v,float y)"
 "{"
   "v=exp2(-v/.3)+exp2(-y/.3);"
   "return-.3*log2(v);"
 "}"
 "float J(vec2 v,float y)"
 "{"
   "y*=v.x;"
   "v.x=abs(v.x);"
   "v.x-=1.5;"
   "return(v.x>0.?"
     "length(v):"
     "abs(v.y))+y;"
 "}"
 "vec3 P(vec2 v)"
 "{"
   "v*=2.;"
   "float f=999.;"
   "for(int i=0;i<36;i++)"
     "{"
       "float u=float(i)+u_t*.3;"
       "vec2 y=B(vec3(u*.2)+vec3(98,48,0)).xy*30.,c=abs(fract(y)-.5)*2.;"
       "y=mix(y,round(y),vec2(e(c.x,2.),e(c.y,2.)));"
       "u=J((v*16.-y)*n(B(vec3(u*.2)).z*E*.6+(floor(u)+e(fract(u),6.))*.5),sin(u)*.3);"
       "f=I(f,abs(u-2.)+.4);"
     "}"
   "f=I(f,(-.03-abs(d(v/1.9+vec2(3.-(u_t/N/20.-10.)*2.,0))))*-16.);"
   "return vec3(.9)-min(f+.26,1.)*.85-(B(vec3(v*3.,u_t)).z*.5+.5)*.2-.1;"
 "}"
 "float Q(vec2 v)"
 "{"
   "return d(v+vec2(3.-(u_t/N/20.-9.)*2.,0));"
 "}"
 "vec3 T(vec2 v)"
 "{"
   "vec3 f=vec3(1);"
   "float u=0.,i=0.;"
   "vec2 y=vec2(3)*n(u_t),c=v,t=normalize(y-c);"
   "const vec2 x=vec2(.0015,0);"
   "for(int r=0;r<128;r++)"
     "{"
       "c=v+t*u;"
       "if(length(c-y)<x.x)"
         "break;"
       "i=max(0.,Q(c));"
       "f=min(f,vec3(pow(i*16.+u*.01,.1)));"
       "if(u>999.)"
         "break;"
       "u+=min(i*.5,length(y-c));"
     "}"
   "if(Q(v)<0.)"
     "f=vec3(1);"
   "return f;"
 "}"
 "vec3 V(vec2 v)"
 "{"
   "float f=d(v+vec2(3.-(u_t/N/20.-9.)*2.,0));"
   "f=smoothstep(f,f+.05,0.);"
   "float u=floor(u_t/N)+e(fract(u_t/N),2.)-f;"
   "vec3 i=vec3(sin(vec3(0,.1,.2)+e(vec3(v*2.,u),1.,1.75-f*.15).x)*.5+.5);"
   "return pow(i,vec3(2));"
 "}"
 "const vec2 W=vec2(14,7);"
 "vec2 Y(vec2 v)"
 "{"
   "vec2 f=vec2(0);"
   "for(float i=-W.x;i<=W.x;i++)"
     "for(float u=-W.x;u<=W.x;u++)"
       "{"
         "vec2 y=vec2(i,u);"
         "float x=length(y)-e(1.-fract(u_t/N),2.);"
         "y/=U;"
         "float t=texture(back_tex,fract(v+y)).x;"
         "f.x+=t*step(W.y,x)*(1.-step(W.x,x));"
         "f.y+=t*(1.-step(W.y,x));"
       "}"
   "return f;"
 "}"
 "float Z(vec2 v)"
 "{"
   "return mix(mix(.69,-.65,smoothstep(0.,1.,v.x)),mix(-.09,-.09,smoothstep(0.,1.,v.x)),smoothstep(0.,1.,v.y));"
 "}"
 "void main()"
 "{"
   "U=vec2(textureSize(comp_tex,0));"
   "z=gl_FragCoord.xy/U;"
   "z-=.5;"
   "z*=2.;"
   "k=gl_FragCoord.xy;"
   "vec3 v=texture(comp_tex,k/U).xyz;"
   "float u=0.;"
   "vec2 y=vec2(z.x*U.x/U.y,z.y);"
   "if(reaction_diffusion)"
     "{"
       "vec3 v=texture(back_tex,k/U).xyz;"
       "vec2 u=Y(k/U)/vec2(G*W.x*W.x,G*W.x*W.x-G*W.y*W.y);"
       "v.x=v.x+.3*(Z(u)*2.-1.);"
       "v.yz=u;"
       "C=clamp(vec4(v+vec3(max(0.,(.1-abs(d(y+vec2(3.-(u_t/N/20.-10.)*2.,0))))*10.),0,0)+e(vec3(y,floor(u_t/N)+e(fract(u_t/N),2.)),1.,1.8)*.2-.05,1),vec4(-1),vec4(1));"
       "return;"
     "}"
   "vec3 f;"
   "if(u_t/N/20.>7.&&u_t/N/20.<8.73)"
     "u=smoothstep(7.,8.,u_t/N/20.),f=L(y),f=mix(f,vec3(1)-f,v);"
   "else if(u_t/N/20.>8.73&&u_t/N/20.<9.)"
     "u=1.,f=w(y*mix(20.,1.,smoothstep(8.5,9.,u_t/N/20.)));"
   "else if(u_t/N/20.>9.&&u_t/N/20.<13.)"
     "{"
       "float v=u_t/N/20.-9.;"
       "if(v<.5)"
         "u=1.,f=pow(T(y),vec3(1.2));"
       "else if(v<1.)"
         "u=1.,f=V(y);"
       "else if(v<2.)"
         ";"
       "else if(v<2.5)"
         "u=1.,f=pow(P(y),vec3(.454545));"
       "else if(v<3.)"
         ";"
       "else if(v<3.5)"
         "{"
           "u=1.;"
           "vec3 v=texture(back_tex,k/U).xyz;"
           "f=vec3(sin((-v.x*.2-.5+v.y*.2)*D-D/2.)*.5+.5)*.6;"
         "}"
       "else"
         " u=1.,f=O(y);"
     "}"
   "else if(u_t/N/20.>13.)"
     "u=1.,f=I(y),f=pow(f,vec3(.454545));"
   "f=mix(vec3(.002,.01,.003),vec3(.95,1.2,1),mix(v,f,u));"
   "C=vec4(f,1);"
 "}";

static const char* song_comp =
 "#version 460\n"
 "layout(local_size_x=256,local_size_y=1,local_size_z=1)in;"
 "layout(std430,binding=0) buffer Aa{vec2 _[];};"
 "layout(location=0) uniform int offs;"
 "const float j=acos(-1.),q=j*2.,at=60./90.;"
 "mat2 n(float v)"
 "{"
   "return mat2(cos(v),-sin(v),sin(v),cos(v));"
 "}"
 "vec3 e(vec3 v,float x,float u)"
 "{"
   "vec4 f=vec4(0);"
   "for(int i=0;i++<5;)"
     "v.yz*=n(4.5),v.xy*=n(1.5),v+=sin(v.zxy),f=(f+vec4(cross(cos(v),sin(v.yzx)),1))/x,v*=u;"
   "return f.xyz/f.w;"
 "}"
 "vec3 A(uvec3 v)"
 "{"
   "v=(v>>8U^v.yzx)*1103773245U;"
   "v=(v>>8U^v.yzx)*1103773245U;"
   "v=(v>>8U^v.yzx)*1103773245U;"
   "return vec3(v)*(1./float(4294967295U));"
 "}"
 "uint r(uint v)"
 "{"
   "v=(v^v>>16)*2146121005U;"
   "v=(v^v>>15)*2221713035U;"
   "return v^v>>16;"
 "}"
 "float e(float v,float y)"
 "{"
   "return v>0.?"
     "1.-exp(-v*y):"
     "0.;"
 "}"
 "float ac[20]=float[](1.,0.,0.,0.,1.,1.,0.,1.,0.,0.,0.,0.,0.,0.,1.,1.,0.,1.,0.,0.),ab[20]=float[](1.,0.,0.,0.,0.,0.,0.,1.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.);"
 "vec2 A(float v,float u,float y)"
 "{"
   "float f=float(64);"
   "vec2 i=vec2(0);"
   "for(float x=0;x<64;x++)"
     "{"
       "vec3 c=A(uvec3(vec3(x,floor((float(v)-x)/f),y)*66456.85725));"
       "vec2 t=6.283*vec2(u*v*exp2(.8*sqrt(-2*log(c.x))*vec2(cos(6.283*c.y),sin(6.283*c.y)))+c.xy);"
       "i+=2*smoothstep(0.,.5,mod(float(v)-x,f)/f)*smoothstep(1.,.5,mod(float(v)-x,f)/f)*vec2(sin(t.x),sin(t.y));"
     "}"
   "return i/float(64);"
 "}"
 "float an(float v)"
 "{"
   "return 440.*pow(2.,v/12.);"
 "}"
 "void main()"
 "{"
   "int v=int(gl_GlobalInvocationID.x)+int(offs);"
   "float f=float(v)/float(44100),u=f/at,y=fract(f/at/20./4.)*at*20.*4.;"
   "vec2 i=vec2(0),x=vec2(0),t=vec2(0);"
   "{"
     "float s=fract(u*4.);"
     "t=exp(-s*6.)*smoothstep(0.,.001,s)*smoothstep(0.,.1,1.-s)*vec2(sin(an(7.)*q*y))*(sin(floor(u)*q)*.5+.5+e(vec3(floor(u*4.)*6.),1.,1.).xy*.2);"
   "}"
   "vec2 c=vec2(0);"
   "for(int v=0;v<5;v++)"
     "{"
       "float u=y-.15*sin(float(v)+y*cos(float(v))*.12),f=u/at;"
       "vec2 i=e(vec3(y,float(v),0),1.,1.).xy*.7;"
       "float x=fract(f/5.),s[16]=float[](-10.,-5.,-2.,2.,-15.,-12.,-7.,-3.,-10.,-3.,0.,5.,-7.,2.,5.,9.);"
       "vec2 t=vec2(0);"
       "for(int v=0;v<4;v++)"
         "{"
           "float y=s[v+int(mod(floor(f/5.),4.))*4];"
           "for(int v=0;v<32;v++)"
             "{"
               "float i=float(v)/32.;"
               "vec2 f=vec2(float(v))/(vec2(1e3)+vec2(cos(.9*q*u),sin(.9*q*u))*5e2)+an(y)*u;"
               "t+=vec2(e(vec3(cos(f.x*q),sin(f.x*q),u*.3),11.,1.).x,e(vec3(cos(f.y*q),sin(f.y*q),u*.3),11.,1.).y)*(1.-i);"
             "}"
         "}"
       "t/=128.;"
       "c+=smoothstep(0.,.2,x)*smoothstep(0.,.6,1.-x)*t*i*.8;"
     "}"
   "c=tanh(c*3.);"
   "vec2 s=vec2(0);"
   "{"
     "float m[16]=float[](0.,2.,7.,10.,0.,5.,7.,9.,0.,2.,5.,9.,3.,5.,9.,10.);"
     "vec2 n=vec2(0);"
     "for(int v=0;v<20;v++)"
       "{"
         "float f=fract(u/5.+v/20.),i=m[r(uint(v+floor(u/5.)*367.))%4+int(mod(floor(u/5.),4.))*4]+12*(r(uint(v+floor(u/5.)*266.))%3),c=an(i)*y;"
         "n+=exp(-f*6.)*smoothstep(0.,.001,f)*smoothstep(0.,.6,1.-f)*e(vec3(cos(c*q),sin(c*q),y*.6),.1,1.).xy*(2e2/an(i));"
       "}"
     "s=n;"
   "}"
   "vec2 l=vec2(0);"
   "{"
     "float m=fract(u*4.),n=ab[int(mod(floor(u*4.),20.))];"
     "l=exp(-m*4.)*smoothstep(0.,.001,m)*smoothstep(0.,.1,1.-m)*vec2(tanh(sin(70.*y-e(m,4.)*60.)*mix(5.,2.,m)))*n;"
     "x+=exp(-m*12.)*n;"
   "}"
   "vec2 m=vec2(0);"
   "{"
     "float z=fract(u*4.),a[4]=float[](-17.,-12.,-7.,-5.);"
     "m=exp(-z*4.)*smoothstep(0.,.001,z)*smoothstep(0.,.1,1.-z)*vec2(tanh(sin(an(a[int(e(vec3(floor(u*4.)*11.+3.),1.,1.).x*8.)%4]-12.)*q*y+sin(220.*y)*pow(sin(3.*y)*.5+.5,9.)*1.6)*12.))*(ac[int(mod(floor(u*4.),20.))]+e(vec3(floor(u*4.)*5.),1.,1.).x*.1);"
   "}"
   "vec2 z=vec2(0);"
   "{"
     "float a=fract(u);"
     "z=exp(-a*5.5)*smoothstep(0.,.001,a)*smoothstep(0.,.1,1.-a)*e(vec3(y)*188888.,1.2,.7).xy*vec2(1,.9);"
   "}"
   "vec2 g=vec2(0);"
   "{"
     "float p[5]=float[](0.,1.,0.,0.,1.);"
     "{"
       "float a=fract(u);"
       "g+=tanh(mix(A(f,1e3,1.),e(vec3(y)*18888.,.9,.4).xy,e(a,2.))*18.)*p[int(mod(floor(u),5.))]*(exp(-a*22.)*smoothstep(0.,.005,a)*smoothstep(0.,.1,1.-a))*vec2(.8,1);"
     "}"
     "{"
       "float a=fract(u-.04);"
       "g+=tanh(e(vec3(y)*22222.,1.6,.5).xy*18.)*p[int(mod(floor(u),5.))]*(exp(-a*8.)*smoothstep(0.,.2,a)*smoothstep(0.,.1,1.-a))*.15*vec2(.6,1);"
     "}"
   "}"
   "vec2 a=vec2(0);"
   "{"
     "float n=fract(u+.5);"
     "a=exp(-n*18.)*smoothstep(0.,.001,n)*smoothstep(0.,.1,1.-n)*tanh(A(y,9900.,3.)*4.)*(fract(floor(u+.5)*11.+.3)*.5+.5)*vec2(1,.4);"
   "}"
   "vec2 n=vec2(0);"
   "{"
     "float b[8]=float[8](-5.,0.,-9.,-7.,-5.,3.,0.,2.),X=an(b[int(floor(u/5.))%8]-36.)*q*y;"
     "n=tanh(e(vec3(cos(X),sin(X),y),1.,1.).xy*12.);"
   "}"
   "y=u/20.;"
   "if(y<1.)"
     "i+=t*.2;"
   "else if(y<2.)"
     "i=i+t*.2+m*.2;"
   "else if(y<4.)"
     "i=i+t*mix(.2,0.,step(3.875,y))+m*.2+c*.25+z*mix(.1*clamp((y-2.)/1.75,0.,1.),0.,step(3.875,y));"
   "else if(y<6.)"
     "i=i+l*.3+t*.2+.05*(1.-x*.8)*n+c*.25+z*.1+g*.2+a*.07;"
   "else if(y<8.)"
     "i=i+l*.3+t*.2+s*.06*pow(clamp((y-6.)/2.,0.,1.),2.)+g*.2;"
   "else if(y<9.)"
     "i=(i+l*.3+t*.2+c*.2+z*mix(.1*pow(clamp((y-8.)/.75,0.,1.),1.6),0.,step(8.75,y)))*step(y,8.75)+s*.06+g*.2;"
   "else if(y<11.)"
     "i=i+l*.3+.25*(1.-x*.6)*m+c*.2+s*.06+z*.05+g*.2+a*.1*pow(clamp((y-9.)/2.,0.,1.),2.3);"
   "else if(y<13.)"
     "i=i+l*.3+t*.2*pow(clamp((y-11.)/2.,0.,1.),1.1)+.25*(1.-x*.6)*m+c*.2+s*.06+z*.05+g*.2+a*.1;"
   "else if(y<14.)"
     "i=i+s*.06*pow(clamp(14.-y,0.,1.),.7)+m*.25+a*.1;"
   "else if(y<14.15)"
     "i+=m*.25;"
   "i=max(vec2(-1),min(vec2(1),tanh(i*1.8)*mix(1.,mix(1.,.85,clamp(y-8.,0.,1.)),step(y,9.))));"
   "_[v]=i;"
 "}";

#endif // SHADER_INCLUDES_H_
